use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Bijwerken via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Gebruiksmonitor",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    models: "Modellen",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Instellingen",
    start_with_windows: "Opstarten met Windows",
    always_on_top: "Altijd op voorgrond",
    reset_position: "Positie herstellen",
    language: "Taal",
    system_default: "Systeemstandaard",
    check_for_updates: "Controleren op updates",
    checking_for_updates: "Controleren op updates...",
    updates: "Updates",
    update_in_progress: "Er is al een updatecontrole bezig.",
    up_to_date: "Je gebruikt al de nieuwste versie.",
    up_to_date_short: "Up-to-date",
    update_failed: "Automatisch bijwerken mislukt",
    applying_update: "Update wordt toegepast...",
    update_to: "Bijwerken naar",
    update_available: "Update beschikbaar",
    update_prompt_now: "Versie {version} is beschikbaar. Wil je nu bijwerken?",
    exit: "Afsluiten",
    show_widget: "Widget tonen",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    token_expired_title: "Claude Code-authenticatiefout",
    token_expired_body: "Voer 'claude' uit in een terminal, gebruik daarna '/login' en volg de stappen. Ververs of herstart de app daarna.",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    antigravity_token_expired_title: "Antigravity-authenticatiefout",
    antigravity_token_expired_body: "Open Antigravity en meld je opnieuw aan. Ververs of herstart de app daarna.",
    codex_window_title: "Codex-gebruiksmonitor",
    antigravity_window_title: "Antigravity-gebruiksmonitor",
    second_suffix: "s",
    usage_display_basis: "Weergavebasis",
    used_percentage: "Gebruikt %",
    remaining_allowance: "Resterend quotum",
    reset_in: "Reset over",
    loading: "Laden",
    fetch_failed: "Ophalen mislukt",
    retrying: "Opnieuw proberen",
    not_configured: "Niet ingesteld",
    not_available: "Niet beschikbaar",
    display_density: "Weergavedichtheid",
    display_density_compact: "Compact",
    standard_level: "Standaard",
    display_density_detailed: "Gedetailleerd",
    short_window_visibility: "Weergave 5u-venster",
    short_window_visibility_always: "Altijd tonen",
    short_window_visibility_warning_only: "Alleen bij overbelasting",
    short_window_visibility_hidden: "Verbergen",
    short_window_alert_sensitivity: "Waarschuwingsgevoeligheid 5u",
    short_window_alert_sensitivity_sensitive: "Gevoelig",
    short_window_alert_sensitivity_relaxed: "Ontspannen",
    weekly_pace_judging: "Wordt beoordeeld",
    weekly_pace_under_pace: "Voor op schema",
    weekly_pace_on_track: "Op schema",
    weekly_pace_slightly_overpacing: "Licht boven schema",
    weekly_pace_overpacing: "Boven schema",
    future_pace_label: "Prognose",
    pace_diff_label: "Afwijking van schema",
    exhaustion_label: "Verwachte uitputting",
    exhaustion_before_reset: "ongeveer {duration} voor reset",
    session_window_label: "5u-venster",
    weekly_window_label: "7d-venster",
    per_day_suffix: "dag",
    per_hour_suffix: "uur",
    pace_used_prefix: "Gebruikt",
    pace_remaining_prefix: "Resterend",
};
