use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    models: "Models",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Full reset",
    antigravity_model: "Antigravity",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    always_on_top: "Always on top",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
    usage_display_basis: "Usage Display",
    used_percentage: "Used %",
    remaining_allowance: "Remaining Allowance",
    reset_in: "Reset in",
    loading: "Loading",
    authentication_expired: "Authentication expired",
    authentication_problem: "Check authentication",
    credentials_unavailable: "Can't verify credentials",
    fetch_failed: "Fetch failed",
    not_available: "Not available",
    display_density: "Display Density",
    display_density_compact: "Compact",
    standard_level: "Standard",
    display_density_detailed: "Detailed",
    short_window_visibility: "5h Window Display",
    short_window_visibility_always: "Always Show",
    short_window_visibility_warning_only: "Only When Overpacing",
    short_window_visibility_hidden: "Hide",
    short_window_alert_sensitivity: "5h Alert Sensitivity",
    short_window_alert_sensitivity_sensitive: "Sensitive",
    short_window_alert_sensitivity_relaxed: "Relaxed",
    weekly_pace_judging: "Judging",
    weekly_pace_under_pace: "Under Pace",
    weekly_pace_on_track: "On Track",
    weekly_pace_slightly_overpacing: "Slightly Overpacing",
    weekly_pace_overpacing: "Overpacing",
    future_pace_label: "Forecast",
    pace_diff_label: "Vs. Plan",
    exhaustion_label: "Est. Exhaustion",
    exhaustion_before_reset: "about {duration} before reset",
    session_window_label: "5h Window",
    weekly_window_label: "7d Window",
    per_day_suffix: "day",
    per_hour_suffix: "hr",
    pace_used_prefix: "Used",
    pace_remaining_prefix: "Remaining",
    popup_layout: "Popup Layout",
    popup_layout_compact: "Compact",
    popup_layout_standard: "Standard",
    app_theme: "Color Theme",
    app_theme_recommended_dark: "Recommended (Dark)",
    app_theme_light: "Light",
    app_theme_high_visibility: "High Visibility",
};
