use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Update via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Usage Monitor",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    displayed_ai: "AI to Display",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Full reset",
    antigravity_model: "Antigravity",
    display_settings: "Display Settings",
    start_with_windows: "Start with Windows",
    always_on_top: "Always on top",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Unknown (usage only)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Help",
    help_display_guide: "How to Read the Display",
    help_ai_quotas: "AI Quotas",
    help_readme: "README",
    help_version_information: "Version Information",
    help_display_guide_body: concat!(
        "Remaining allowance / Used percentage\n",
        "The percentage follows the display basis selected in Display Settings.\n\n",
        "5h / 7d / Mo\n",
        "These are five-hour, seven-day, and monthly quota windows. A row is omitted when it has nothing to display.\n\n",
        "Time display\n",
        "Relative shows elapsed time for Used percentage, or time until reset for Remaining allowance. Date & time shows the local reset date and time instead.\n\n",
        "Pace guidance\n",
        "Pace, difference from schedule, and warnings such as Overusing are guidance based on your usage pace.\n\n",
        "Statuses\n",
        "Zero usage is not a fetch failure. Not applicable means that quota does not exist for the provider; it is different from hiding a quota in settings."
    ),
    help_ai_quotas_intro: "Each provider has its own quota system. Similar names do not mean that quotas are shared.",
    help_provider_notes: &[
        ProviderHelp {
            name: "Claude",
            description: "Shows the shared 5h and 7d quotas for the Claude / Claude Code account.",
        },
        ProviderHelp {
            name: "Codex",
            description: "Shows the 5h and 7d quotas available through Codex CLI. These are separate from ChatGPT app quotas.",
        },
        ProviderHelp {
            name: "Antigravity",
            description: "Shows Antigravity quotas. These are separate from standalone Gemini quotas.",
        },
        ProviderHelp {
            name: "GitHub Copilot",
            description: "Shows monthly GitHub Copilot AI Credits. The selected plan determines the allowance; Unknown shows gross usage only. GitHub Copilot is different from Microsoft Copilot.",
        },
    ],
    check_for_updates: "Check for Updates",
    checking_for_updates: "Checking for Updates...",
    updates: "Updates",
    update_in_progress: "An update check is already in progress.",
    up_to_date: "You already have the latest version.",
    up_to_date_short: "Up to date",
    update_failed: "Unable to update automatically",
    applying_update: "Applying update...",
    update_to: "Update to",
    update_available: "Update available",
    update_prompt_now: "Version {version} is available. Do you want to update now?",
    exit: "Exit",
    show_widget: "Show Widget",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "Mo",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Claude Code Auth Error",
    token_expired_body: "Run 'claude' in a terminal, then use '/login' and follow the prompts. After that, refresh or restart this app.",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    antigravity_token_expired_title: "Antigravity Auth Error",
    antigravity_token_expired_body: "Open Antigravity and sign in again. After that, refresh or restart this app.",
    codex_window_title: "Codex Usage Monitor",
    antigravity_window_title: "Antigravity Usage Monitor",
    second_suffix: "s",
    usage_display_basis: "Usage Display",
    used_percentage: "Used %",
    remaining_allowance: "Remaining Allowance",
    reset_in: "Reset in",
    reset_in_separator: " ",
    reset_display: "Time Display",
    reset_display_relative: "Relative",
    reset_display_datetime: "Date and Time",
    reset_datetime_day: "Reset {day} ({weekday}) at {time}",
    reset_datetime_month_day: "Reset {month}/{day} ({weekday}) at {time}",
    reset_datetime_year_month_day: "Reset {year}/{month}/{day} ({weekday}) at {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    elapsed: "Elapsed",
    loading: "Loading",
    authentication_expired: "Authentication expired",
    authentication_problem: "Check authentication",
    credentials_unavailable: "Can't verify credentials",
    fetch_failed: "Fetch failed",
    not_available: "Not available",
    display_density: "Display Density",
    display_density_compact: "Compact",
    standard_level: "Standard",
    display_density_detailed: "Detailed",
    short_window_visibility: "Display Method",
    short_window_visibility_always: "Always Show",
    short_window_visibility_warning_only: "Only When Overpacing",
    short_window_visibility_hidden: "Hide",
    short_window_alert_sensitivity: "Alert Sensitivity",
    short_window_alert_sensitivity_sensitive: "Sensitive",
    short_window_alert_sensitivity_relaxed: "Relaxed",
    weekly_pace_judging: "Judging",
    weekly_pace_under_pace: "Under Pace",
    weekly_pace_on_track: "On Track",
    weekly_pace_slightly_overpacing: "Slightly Overpacing",
    weekly_pace_overpacing: "Overpacing",
    future_pace_label: "Forecast",
    pace_diff_label: "Vs. Plan",
    exhaustion_label: "Est. Exhaustion",
    exhaustion_before_reset: "about {duration} before reset",
    session_window_label: "5h Window",
    weekly_window_label: "7d Window",
    per_day_suffix: "day",
    per_hour_suffix: "hr",
    pace_used_prefix: "Used",
    pace_remaining_prefix: "Remaining",
    popup_layout: "Popup Layout",
    popup_layout_compact: "Compact",
    popup_layout_standard: "Standard",
    app_theme: "Color Theme",
    app_theme_recommended_dark: "Dark",
    app_theme_light: "Light",
    app_theme_high_visibility: "High Visibility",
};
