use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mettre à jour avec WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Moniteur d'utilisation Claude Code",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    models: "Modeles",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Paramètres",
    start_with_windows: "Démarrer avec Windows",
    always_on_top: "Toujours au premier plan",
    reset_position: "Réinitialiser la position",
    language: "Langue",
    system_default: "Par défaut du système",
    check_for_updates: "Vérifier les mises à jour",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d'effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now: "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Erreur d'authentification",
    token_expired_body: "Exécutez 'claude' dans un terminal, puis utilisez '/login' et suivez les instructions. Ensuite, actualisez ou redémarrez cette application.",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    antigravity_token_expired_title: "Erreur d'authentification Antigravity",
    antigravity_token_expired_body: "Ouvrez Antigravity et reconnectez-vous. Ensuite, actualisez ou redemarrez cette application.",
    codex_window_title: "Moniteur d'utilisation Codex",
    antigravity_window_title: "Moniteur d'utilisation Antigravity",
    second_suffix: "s",
    usage_display_basis: "Base d'affichage",
    used_percentage: "% utilisé",
    remaining_allowance: "Quota restant",
    reset_in: "Réinit. dans",
    loading: "Chargement",
    fetch_failed: "Échec de récupération",
    retrying: "Nouvelle tentative",
    not_configured: "Non configuré",
    not_available: "Non disponible",
    display_density: "Densité d'affichage",
    display_density_compact: "Compact",
    standard_level: "Standard",
    display_density_detailed: "Détaillé",
    short_window_visibility: "Affichage fenêtre 5h",
    short_window_visibility_always: "Toujours afficher",
    short_window_visibility_warning_only: "Seulement en surconsommation",
    short_window_visibility_hidden: "Masquer",
    short_window_alert_sensitivity: "Sensibilité d'alerte 5h",
    short_window_alert_sensitivity_sensitive: "Sensible",
    short_window_alert_sensitivity_relaxed: "Détendue",
};
