use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mettre à jour avec WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Moniteur d'utilisation Claude Code",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    displayed_ai: "IA à afficher",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Réinitialisation complète",
    antigravity_model: "Antigravity",
    display_settings: "Paramètres d’affichage",
    start_with_windows: "Démarrer avec Windows",
    always_on_top: "Toujours au premier plan",
    reset_position: "Réinitialiser la position",
    language: "Langue",
    system_default: "Par défaut du système",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Inconnu (utilisation uniquement)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Aide",
    help_display_guide: "Comprendre l’affichage",
    help_ai_quotas: "Quotas d’IA",
    help_readme: "README",
    help_version_information: "Informations sur la version",
    help_display_guide_body: concat!(
        "Quota restant / Pourcentage utilisé\n",
        "Le pourcentage suit la base choisie dans les paramètres d’affichage.\n\n",
        "5h / 7d / Mo\n",
        "Ce sont les quotas sur cinq heures, sept jours et un mois. Une ligne sans contenu est omise.\n\n",
        "Affichage du temps\n",
        "Relatif affiche le temps écoulé pour Utilisé, ou le temps avant réinitialisation pour Restant. Date et heure affiche plutôt la réinitialisation en heure locale.\n\n",
        "Indications de rythme\n",
        "Le rythme, l’écart au calendrier et les avertissements sont des repères fondés sur votre cadence d’utilisation.\n\n",
        "États\n",
        "Une utilisation nulle n’est pas un échec de récupération. Non applicable signifie que ce quota n’existe pas chez le fournisseur, ce qui diffère d’un quota masqué."
    ),
    help_ai_quotas_intro: "Chaque fournisseur possède son propre système de quotas. Des noms proches ne signifient pas que les quotas sont partagés.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Affiche les quotas 5h et 7j partagés du compte Claude / Claude Code." },
        ProviderHelp { name: "Codex", description: "Affiche les quotas 5h et 7j accessibles via Codex CLI. Ils sont distincts des quotas de l’application ChatGPT." },
        ProviderHelp { name: "Antigravity", description: "Affiche les quotas Antigravity. Ils sont distincts des quotas Gemini autonomes." },
        ProviderHelp { name: "GitHub Copilot", description: "Affiche les AI Credits mensuels de GitHub Copilot. L’offre choisie détermine le quota ; Inconnu affiche seulement l’utilisation brute. GitHub Copilot est distinct de Microsoft Copilot." },
    ],
    check_for_updates: "Vérifier les mises à jour",
    checking_for_updates: "Vérification des mises à jour...",
    updates: "Mises à jour",
    update_in_progress: "Une vérification de mise à jour est déjà en cours.",
    up_to_date: "Vous utilisez déjà la version la plus récente.",
    up_to_date_short: "À jour",
    update_failed: "Impossible d'effectuer la mise à jour automatiquement",
    applying_update: "Application de la mise à jour...",
    update_to: "Mettre à jour vers",
    update_available: "Mise à jour disponible",
    update_prompt_now: "La version {version} est disponible. Voulez-vous mettre à jour maintenant ?",
    exit: "Quitter",
    show_widget: "Afficher le widget",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "M",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Erreur d'authentification",
    token_expired_body: "Exécutez 'claude' dans un terminal, puis utilisez '/login' et suivez les instructions. Ensuite, actualisez ou redémarrez cette application.",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    antigravity_token_expired_title: "Erreur d'authentification Antigravity",
    antigravity_token_expired_body: "Ouvrez Antigravity et reconnectez-vous. Ensuite, actualisez ou redemarrez cette application.",
    codex_window_title: "Moniteur d'utilisation Codex",
    antigravity_window_title: "Moniteur d'utilisation Antigravity",
    second_suffix: "s",
    usage_display_basis: "Base d'affichage",
    used_percentage: "% utilisé",
    remaining_allowance: "Quota restant",
    reset_in: "Réinit. dans",
    reset_in_separator: " ",
    reset_display: "Affichage de l’heure",
    reset_display_relative: "Relatif",
    reset_display_datetime: "Date et heure",
    reset_datetime_day: "Réinit. le {day} ({weekday}) à {time}",
    reset_datetime_month_day: "Réinit. le {day}/{month} ({weekday}) à {time}",
    reset_datetime_year_month_day: "Réinit. le {day}/{month}/{year} ({weekday}) à {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["dim", "lun", "mar", "mer", "jeu", "ven", "sam"],
    elapsed: "Écoulé",
    loading: "Chargement",
    authentication_expired: "Authentification expirée",
    authentication_problem: "Vérifiez l’authentification",
    credentials_unavailable: "Identifiants non vérifiables",
    fetch_failed: "Échec de récupération",
    not_available: "Non disponible",
    display_density: "Densité d'affichage",
    display_density_compact: "Compact",
    standard_level: "Standard",
    display_density_detailed: "Détaillé",
    short_window_visibility: "Mode d’affichage",
    short_window_visibility_always: "Toujours afficher",
    short_window_visibility_warning_only: "Seulement en surconsommation",
    short_window_visibility_hidden: "Masquer",
    short_window_alert_sensitivity: "Sensibilité des alertes",
    short_window_alert_sensitivity_sensitive: "Sensible",
    short_window_alert_sensitivity_relaxed: "Détendue",
    weekly_pace_judging: "Évaluation en cours",
    weekly_pace_under_pace: "En avance",
    weekly_pace_on_track: "Dans les temps",
    weekly_pace_slightly_overpacing: "Légèrement en surconsommation",
    weekly_pace_overpacing: "En surconsommation",
    future_pace_label: "Prévision",
    pace_diff_label: "Écart au plan",
    exhaustion_label: "Épuisement estimé",
    exhaustion_before_reset: "environ {duration} avant réinitialisation",
    session_window_label: "Fenêtre 5h",
    weekly_window_label: "Fenêtre 7j",
    per_day_suffix: "j",
    per_hour_suffix: "h",
    pace_used_prefix: "Utilisé",
    pace_remaining_prefix: "Restant",
    popup_layout: "Disposition du popup",
    popup_layout_compact: "Compact",
    popup_layout_standard: "Standard",
    app_theme: "Thème de couleur",
    app_theme_recommended_dark: "Sombre",
    app_theme_light: "Clair",
    app_theme_high_visibility: "Haute visibilité",
};
