use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Nutzungsmonitor",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    displayed_ai: "Anzuzeigende KI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Vollständiger Reset",
    antigravity_model: "Antigravity",
    display_settings: "Anzeigeeinstellungen",
    start_with_windows: "Mit Windows starten",
    always_on_top: "Immer im Vordergrund",
    reset_position: "Position zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Unbekannt (nur Nutzung)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Hilfe",
    help_display_guide: "Anzeige verstehen",
    help_ai_quotas: "KI-Kontingente",
    help_readme: "README",
    help_version_information: "Versionsinformationen",
    help_display_guide_body: concat!(
        "Verbleibend / Verwendeter Anteil\n",
        "Der Prozentwert folgt der gewählten Anzeigebasis.\n\n",
        "5h / 7d / Mo\n",
        "Dies sind Kontingente für fünf Stunden, sieben Tage und einen Monat. Leere Zeilen werden ausgelassen.\n\n",
        "Zeitanzeige\n",
        "Relativ zeigt bei Verwendet die verstrichene Zeit, bei Verbleibend die Zeit bis zum Reset. Datum und Uhrzeit zeigt stattdessen den lokalen Resetzeitpunkt.\n\n",
        "Tempo-Hinweise\n",
        "Richtwert, Planabweichung und Warnungen sind Orientierungshilfen auf Grundlage Ihres Nutzungstempos.\n\n",
        "Status\n",
        "Null Nutzung ist kein Abruffehler. Nicht verfügbar bedeutet, dass dieses Kontingent beim Anbieter nicht existiert; dies unterscheidet sich vom Ausblenden in den Einstellungen."
    ),
    help_ai_quotas_intro: "Jeder Anbieter hat ein eigenes Kontingentsystem. Ähnliche Namen bedeuten keine gemeinsamen Kontingente.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Zeigt die gemeinsamen 5h- und 7d-Kontingente des Claude-/Claude-Code-Kontos." },
        ProviderHelp { name: "Codex", description: "Zeigt die über Codex CLI verfügbaren 5h- und 7d-Kontingente. Diese sind von den Kontingenten der ChatGPT-App getrennt." },
        ProviderHelp { name: "Antigravity", description: "Zeigt die Antigravity-Kontingente. Diese sind von eigenständigen Gemini-Kontingenten getrennt." },
        ProviderHelp { name: "GitHub Copilot", description: "Zeigt monatliche GitHub Copilot AI Credits. Der gewählte Tarif bestimmt das Kontingent; Unbekannt zeigt nur die Bruttonutzung. GitHub Copilot ist nicht Microsoft Copilot." },
    ],
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Widget anzeigen",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "Mon",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Authentifizierungsfehler",
    token_expired_body: "Führen Sie 'claude' in einem Terminal aus, verwenden Sie dann '/login' und folgen Sie den Anweisungen. Aktualisieren oder starten Sie diese App anschließend neu.",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    antigravity_token_expired_title: "Antigravity-Authentifizierungsfehler",
    antigravity_token_expired_body: "Offnen Sie Antigravity und melden Sie sich erneut an. Aktualisieren oder starten Sie diese App anschliessend neu.",
    codex_window_title: "Codex-Nutzungsmonitor",
    antigravity_window_title: "Antigravity-Nutzungsmonitor",
    second_suffix: "s",
    usage_display_basis: "Anzeigebasis",
    used_percentage: "Genutzt (%)",
    remaining_allowance: "Verbleibendes Kontingent",
    reset_in: "Reset in",
    reset_in_separator: " ",
    reset_display: "Zeitanzeige",
    reset_display_relative: "Relativ",
    reset_display_datetime: "Datum und Uhrzeit",
    reset_datetime_day: "Reset am {day}. ({weekday}) um {time}",
    reset_datetime_month_day: "Reset am {day}.{month}. ({weekday}) um {time}",
    reset_datetime_year_month_day: "Reset am {day}.{month}.{year} ({weekday}) um {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"],
    elapsed: "Vergangen",
    loading: "Wird geladen",
    authentication_expired: "Authentifizierung abgelaufen",
    authentication_problem: "Authentifizierung prüfen",
    credentials_unavailable: "Anmeldedaten nicht prüfbar",
    fetch_failed: "Abruf fehlgeschlagen",
    not_available: "Nicht verfügbar",
    display_density: "Anzeigedichte",
    display_density_compact: "Kompakt",
    standard_level: "Standard",
    display_density_detailed: "Detailliert",
    short_window_visibility: "Anzeigemethode",
    short_window_visibility_always: "Immer anzeigen",
    short_window_visibility_warning_only: "Nur bei Überlastung",
    short_window_visibility_hidden: "Ausblenden",
    short_window_alert_sensitivity: "Warnempfindlichkeit",
    short_window_alert_sensitivity_sensitive: "Empfindlich",
    short_window_alert_sensitivity_relaxed: "Gelassen",
    weekly_pace_judging: "Wird bewertet",
    weekly_pace_under_pace: "Im Plus",
    weekly_pace_on_track: "Im Plan",
    weekly_pace_slightly_overpacing: "Leicht über Plan",
    weekly_pace_overpacing: "Über Plan",
    future_pace_label: "Prognose",
    pace_diff_label: "Abw. vom Plan",
    exhaustion_label: "Vorauss. Erschöpfung",
    exhaustion_before_reset: "etwa {duration} vor Reset",
    session_window_label: "5-Std-Fenster",
    weekly_window_label: "7-Tage-Fenster",
    per_day_suffix: "Tag",
    per_hour_suffix: "Std",
    pace_used_prefix: "Genutzt",
    pace_remaining_prefix: "Verbleibend",
    popup_layout: "Popup-Layout",
    popup_layout_compact: "Kompakt",
    popup_layout_standard: "Standard",
    app_theme: "Farbschema",
    app_theme_recommended_dark: "Dunkel",
    app_theme_light: "Hell",
    app_theme_high_visibility: "Hoher Kontrast",
};
