use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Mit WinGet aktualisieren";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code Nutzungsmonitor",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    models: "Modelle",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Vollständiger Reset",
    antigravity_model: "Antigravity",
    settings: "Einstellungen",
    start_with_windows: "Mit Windows starten",
    always_on_top: "Immer im Vordergrund",
    reset_position: "Position zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    check_for_updates: "Nach Updates suchen",
    checking_for_updates: "Suche nach Updates...",
    updates: "Updates",
    update_in_progress: "Eine Update-Prüfung läuft bereits.",
    up_to_date: "Sie verwenden bereits die neueste Version.",
    up_to_date_short: "Aktuell",
    update_failed: "Automatisches Update war nicht möglich",
    applying_update: "Update wird installiert...",
    update_to: "Aktualisieren auf",
    update_available: "Update verfügbar",
    update_prompt_now: "Version {version} ist verfügbar. Möchten Sie jetzt aktualisieren?",
    exit: "Beenden",
    show_widget: "Widget anzeigen",
    session_window: "5h",
    weekly_window: "7d",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Authentifizierungsfehler",
    token_expired_body: "Führen Sie 'claude' in einem Terminal aus, verwenden Sie dann '/login' und folgen Sie den Anweisungen. Aktualisieren oder starten Sie diese App anschließend neu.",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    antigravity_token_expired_title: "Antigravity-Authentifizierungsfehler",
    antigravity_token_expired_body: "Offnen Sie Antigravity und melden Sie sich erneut an. Aktualisieren oder starten Sie diese App anschliessend neu.",
    codex_window_title: "Codex-Nutzungsmonitor",
    antigravity_window_title: "Antigravity-Nutzungsmonitor",
    second_suffix: "s",
    usage_display_basis: "Anzeigebasis",
    used_percentage: "Genutzt (%)",
    remaining_allowance: "Verbleibendes Kontingent",
    reset_in: "Reset in",
    loading: "Wird geladen",
    fetch_failed: "Abruf fehlgeschlagen",
    retrying: "Erneuter Versuch",
    not_configured: "Nicht eingerichtet",
    not_available: "Nicht verfügbar",
    display_density: "Anzeigedichte",
    display_density_compact: "Kompakt",
    standard_level: "Standard",
    display_density_detailed: "Detailliert",
    short_window_visibility: "5-Std-Fenster-Anzeige",
    short_window_visibility_always: "Immer anzeigen",
    short_window_visibility_warning_only: "Nur bei Überlastung",
    short_window_visibility_hidden: "Ausblenden",
    short_window_alert_sensitivity: "5-Std-Warnempfindlichkeit",
    short_window_alert_sensitivity_sensitive: "Empfindlich",
    short_window_alert_sensitivity_relaxed: "Gelassen",
    weekly_pace_judging: "Wird bewertet",
    weekly_pace_under_pace: "Im Plus",
    weekly_pace_on_track: "Im Plan",
    weekly_pace_slightly_overpacing: "Leicht über Plan",
    weekly_pace_overpacing: "Über Plan",
    future_pace_label: "Prognose",
    pace_diff_label: "Abw. vom Plan",
    exhaustion_label: "Vorauss. Erschöpfung",
    exhaustion_before_reset: "etwa {duration} vor Reset",
    session_window_label: "5-Std-Fenster",
    weekly_window_label: "7-Tage-Fenster",
    per_day_suffix: "Tag",
    per_hour_suffix: "Std",
    pace_used_prefix: "Genutzt",
    pace_remaining_prefix: "Verbleibend",
    popup_layout: "Popup-Layout",
    popup_layout_compact: "Kompakt",
    popup_layout_standard: "Standard",
    app_theme: "Farbschema",
    app_theme_recommended_dark: "Empfohlen (Dunkel)",
    app_theme_light: "Hell",
    app_theme_high_visibility: "Hoher Kontrast",
};
