use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量モニター",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    displayed_ai: "表示するAI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "フルリセット",
    antigravity_model: "Antigravity",
    display_settings: "表示設定",
    start_with_windows: "Windowsと同時に開始",
    always_on_top: "常に手前に表示",
    reset_position: "位置をリセット",
    language: "言語",
    system_default: "システム既定",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "不明（使用量のみ）",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "ヘルプ",
    help_readme_placeholder: "（仮）README",
    help_update_placeholder: "（仮）アプリの更新",
    help_version_placeholder: "（仮）バージョン情報",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "月",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
    usage_display_basis: "表示基準",
    used_percentage: "使用済み率",
    remaining_allowance: "残り利用枠",
    reset_in: "あと",
    reset_in_separator: "",
    reset_display: "時間表示",
    reset_display_relative: "相対",
    reset_display_datetime: "日時",
    reset_datetime_day: "{day}({weekday}) {time}リセット",
    reset_datetime_month_day: "{month}月{day}日({weekday}) {time}リセット",
    reset_datetime_year_month_day: "{year}年{month}月{day}日({weekday}) {time}リセット",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["日", "月", "火", "水", "木", "金", "土"],
    elapsed: "経過",
    loading: "取得中",
    authentication_expired: "認証切れ",
    authentication_problem: "認証を確認してください",
    credentials_unavailable: "認証情報を確認できません",
    fetch_failed: "取得失敗",
    not_available: "対象なし",
    display_density: "表示密度",
    display_density_compact: "簡潔",
    standard_level: "標準",
    display_density_detailed: "詳細",
    short_window_visibility: "表示方法",
    short_window_visibility_always: "常に表示",
    short_window_visibility_warning_only: "使いすぎのときだけ",
    short_window_visibility_hidden: "表示しない",
    short_window_alert_sensitivity: "警告感度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "鈍感",
    weekly_pace_judging: "判定中",
    weekly_pace_under_pace: "余裕あり",
    weekly_pace_on_track: "予定どおり",
    weekly_pace_slightly_overpacing: "やや使いすぎ",
    weekly_pace_overpacing: "使いすぎ",
    future_pace_label: "目安",
    pace_diff_label: "予定との差",
    exhaustion_label: "枯渇見込み",
    exhaustion_before_reset: "リセットの約{duration}前",
    session_window_label: "5時間枠",
    weekly_window_label: "7日枠",
    per_day_suffix: "日",
    per_hour_suffix: "時",
    pace_used_prefix: "使用",
    pace_remaining_prefix: "残り",
    popup_layout: "表示レイアウト",
    popup_layout_compact: "コンパクト",
    popup_layout_standard: "標準",
    app_theme: "配色",
    app_theme_recommended_dark: "ダーク",
    app_theme_light: "ライト",
    app_theme_high_visibility: "高視認性",
};
