use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet で更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量モニター",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    models: "モデル",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "Windows と同時に開始",
    always_on_top: "常に手前に表示",
    reset_position: "位置をリセット",
    language: "言語",
    system_default: "システム既定",
    check_for_updates: "更新を確認",
    checking_for_updates: "更新を確認しています...",
    updates: "更新",
    update_in_progress: "更新確認は既に実行中です。",
    up_to_date: "既に最新バージョンです。",
    up_to_date_short: "最新です",
    update_failed: "自動更新を完了できませんでした",
    applying_update: "更新を適用しています...",
    update_to: "更新先",
    update_available: "更新が利用可能です",
    update_prompt_now: "バージョン {version} が利用可能です。今すぐ更新しますか？",
    exit: "終了",
    show_widget: "ウィジェットを表示",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    token_expired_title: "認証エラー",
    token_expired_body: "ターミナルで 'claude' を実行し、'/login' を使って案内に従ってください。その後、このアプリを更新するか再起動してください。",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    antigravity_token_expired_title: "Antigravity 認証エラー",
    antigravity_token_expired_body: "Antigravity を開いて再度サインインしてください。その後、このアプリを更新するか再起動してください。",
    codex_window_title: "Codex 使用量モニター",
    antigravity_window_title: "Antigravity 使用量モニター",
    second_suffix: "秒",
    usage_display_basis: "表示基準",
    used_percentage: "使用済み率",
    remaining_allowance: "残り利用枠",
    reset_in: "リセットまで",
    loading: "取得中",
    fetch_failed: "取得失敗",
    retrying: "再試行中",
    not_configured: "未設定",
    not_available: "対象なし",
    display_density: "表示密度",
    display_density_compact: "簡潔",
    standard_level: "標準",
    display_density_detailed: "詳細",
    short_window_visibility: "5時間枠の表示",
    short_window_visibility_always: "常に表示",
    short_window_visibility_warning_only: "使いすぎのときだけ",
    short_window_visibility_hidden: "表示しない",
    short_window_alert_sensitivity: "5時間枠の警告感度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "鈍感",
};
