use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 사용량 모니터",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    displayed_ai: "표시할 AI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "전체 재설정",
    antigravity_model: "Antigravity",
    display_settings: "표시 설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    always_on_top: "항상 위에 표시",
    reset_position: "위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "알 수 없음 (사용량만)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "도움말",
    help_display_guide: "표시 읽는 방법",
    help_ai_quotas: "AI 사용 한도",
    help_readme: "README",
    help_version_information: "버전 정보",
    help_display_guide_body: concat!(
        "남은 한도 / 사용률\n",
        "백분율은 표시 설정에서 선택한 기준을 따릅니다.\n\n",
        "5h / 7d / Mo\n",
        "5시간, 7일, 월간 사용 한도입니다. 표시할 내용이 없는 행은 생략됩니다.\n\n",
        "시간 표시\n",
        "상대는 사용률에서 경과 시간을, 남은 한도에서 재설정까지 남은 시간을 표시합니다. 날짜 및 시간은 대신 현지 재설정 시각을 표시합니다.\n\n",
        "사용 속도 안내\n",
        "기준 속도, 일정과의 차이, 과다 사용 등의 경고는 사용 속도를 판단하기 위한 참고 정보입니다.\n\n",
        "상태 구분\n",
        "사용량 0은 가져오기 실패가 아닙니다. 해당 없음은 제공자에게 그 한도가 없다는 뜻이며 설정에서 숨긴 것과 다릅니다."
    ),
    help_ai_quotas_intro: "제공자마다 사용 한도 체계가 다릅니다. 이름이 비슷해도 한도를 공유한다는 뜻은 아닙니다.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Claude / Claude Code 계정이 공유하는 5h 및 7d 사용 한도를 표시합니다." },
        ProviderHelp { name: "Codex", description: "Codex CLI에서 확인할 수 있는 5h 및 7d 한도입니다. ChatGPT 앱의 사용 한도와는 별개입니다." },
        ProviderHelp { name: "Antigravity", description: "Antigravity의 사용 한도입니다. 독립형 Gemini의 사용 한도와는 별개입니다." },
        ProviderHelp { name: "GitHub Copilot", description: "GitHub Copilot의 월간 AI Credits입니다. 선택한 요금제에 따라 한도를 표시하며, 요금제를 알 수 없으면 총사용량만 표시합니다. Microsoft Copilot과는 다른 서비스입니다." },
    ],
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯 표시",
    session_window: "5시간",
    weekly_window: "7일",
    monthly_window: "월",
    now: "지금",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    antigravity_token_expired_title: "Antigravity 인증 오류",
    antigravity_token_expired_body: "Antigravity를 열고 다시 로그인하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_window_title: "Codex 사용량 모니터",
    antigravity_window_title: "Antigravity 사용량 모니터",
    second_suffix: "초",
    usage_display_basis: "표시 기준",
    used_percentage: "사용률",
    remaining_allowance: "남은 한도",
    reset_in: "초기화까지",
    reset_in_separator: " ",
    reset_display: "시간 표시",
    reset_display_relative: "상대",
    reset_display_datetime: "날짜 및 시간",
    reset_datetime_day: "{day}({weekday}) {time} 초기화",
    reset_datetime_month_day: "{month}월 {day}일({weekday}) {time} 초기화",
    reset_datetime_year_month_day: "{year}년 {month}월 {day}일({weekday}) {time} 초기화",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["일", "월", "화", "수", "목", "금", "토"],
    elapsed: "경과",
    loading: "불러오는 중",
    authentication_expired: "인증 만료",
    authentication_problem: "인증을 확인해 주세요",
    credentials_unavailable: "인증 정보를 확인할 수 없음",
    fetch_failed: "가져오기 실패",
    not_available: "해당 없음",
    display_density: "표시 밀도",
    display_density_compact: "간결",
    standard_level: "표준",
    display_density_detailed: "상세",
    short_window_visibility: "표시 방법",
    short_window_visibility_always: "항상 표시",
    short_window_visibility_warning_only: "과다 사용 시에만",
    short_window_visibility_hidden: "표시 안 함",
    short_window_alert_sensitivity: "경고 민감도",
    short_window_alert_sensitivity_sensitive: "민감",
    short_window_alert_sensitivity_relaxed: "둔감",
    weekly_pace_judging: "판정 중",
    weekly_pace_under_pace: "여유 있음",
    weekly_pace_on_track: "예정대로",
    weekly_pace_slightly_overpacing: "약간 과다 사용",
    weekly_pace_overpacing: "과다 사용",
    future_pace_label: "향후 예상",
    pace_diff_label: "예정 대비 차이",
    exhaustion_label: "소진 예상",
    exhaustion_before_reset: "초기화 약 {duration} 전",
    session_window_label: "5시간 창",
    weekly_window_label: "7일 창",
    per_day_suffix: "일",
    per_hour_suffix: "시",
    pace_used_prefix: "사용",
    pace_remaining_prefix: "남음",
    popup_layout: "팝업 레이아웃",
    popup_layout_compact: "간결",
    popup_layout_standard: "표준",
    app_theme: "색상 테마",
    app_theme_recommended_dark: "다크",
    app_theme_light: "라이트",
    app_theme_high_visibility: "고가시성",
};
