use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "WinGet으로 업데이트";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 사용량 모니터",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    displayed_ai: "표시할 AI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "전체 재설정",
    antigravity_model: "Antigravity",
    display_settings: "표시 설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    always_on_top: "항상 위에 표시",
    reset_position: "위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "알 수 없음 (사용량만)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "도움말",
    help_readme_placeholder: "(임시) README",
    help_update_placeholder: "(임시) 앱 업데이트",
    help_version_placeholder: "(임시) 버전 정보",
    check_for_updates: "업데이트 확인",
    checking_for_updates: "업데이트 확인 중...",
    updates: "업데이트",
    update_in_progress: "이미 업데이트 확인이 진행 중입니다.",
    up_to_date: "이미 최신 버전입니다.",
    up_to_date_short: "최신",
    update_failed: "자동 업데이트를 완료할 수 없습니다",
    applying_update: "업데이트 적용 중...",
    update_to: "업데이트 대상",
    update_available: "업데이트 사용 가능",
    update_prompt_now: "버전 {version}을 사용할 수 있습니다. 지금 업데이트하시겠습니까?",
    exit: "종료",
    show_widget: "위젯 표시",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    token_expired_title: "인증 오류",
    token_expired_body: "터미널에서 'claude'를 실행한 다음 '/login'을 사용하고 안내에 따라 진행하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    antigravity_token_expired_title: "Antigravity 인증 오류",
    antigravity_token_expired_body: "Antigravity를 열고 다시 로그인하세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    codex_window_title: "Codex 사용량 모니터",
    antigravity_window_title: "Antigravity 사용량 모니터",
    second_suffix: "초",
    usage_display_basis: "표시 기준",
    used_percentage: "사용률",
    remaining_allowance: "남은 한도",
    reset_in: "초기화까지",
    loading: "불러오는 중",
    authentication_expired: "인증 만료",
    authentication_problem: "인증을 확인해 주세요",
    credentials_unavailable: "인증 정보를 확인할 수 없음",
    fetch_failed: "가져오기 실패",
    not_available: "해당 없음",
    display_density: "표시 밀도",
    display_density_compact: "간결",
    standard_level: "표준",
    display_density_detailed: "상세",
    short_window_visibility: "표시 방법",
    short_window_visibility_always: "항상 표시",
    short_window_visibility_warning_only: "과다 사용 시에만",
    short_window_visibility_hidden: "표시 안 함",
    short_window_alert_sensitivity: "경고 민감도",
    short_window_alert_sensitivity_sensitive: "민감",
    short_window_alert_sensitivity_relaxed: "둔감",
    weekly_pace_judging: "판정 중",
    weekly_pace_under_pace: "여유 있음",
    weekly_pace_on_track: "예정대로",
    weekly_pace_slightly_overpacing: "약간 과다 사용",
    weekly_pace_overpacing: "과다 사용",
    future_pace_label: "향후 예상",
    pace_diff_label: "예정 대비 차이",
    exhaustion_label: "소진 예상",
    exhaustion_before_reset: "초기화 약 {duration} 전",
    session_window_label: "5시간 창",
    weekly_window_label: "7일 창",
    per_day_suffix: "일",
    per_hour_suffix: "시",
    pace_used_prefix: "사용",
    pace_remaining_prefix: "남음",
    popup_layout: "팝업 레이아웃",
    popup_layout_compact: "간결",
    popup_layout_standard: "표준",
    app_theme: "색상 테마",
    app_theme_recommended_dark: "다크",
    app_theme_light: "라이트",
    app_theme_high_visibility: "고가시성",
};
