use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de Uso do Claude Code",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    models: "Modelos",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configurações",
    start_with_windows: "Iniciar com o Windows",
    always_on_top: "Sempre no topo",
    reset_position: "Redefinir Posição",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    token_expired_title: "Erro de Autenticação do Claude Code",
    token_expired_body: "Execute 'claude' em um terminal, use '/login' e siga as instruções. Depois disso, atualize ou reinicie este aplicativo.",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    antigravity_token_expired_title: "Erro de Autenticação do Antigravity",
    antigravity_token_expired_body: "Abra o Antigravity e entre novamente. Depois disso, atualize ou reinicie este aplicativo.",
    codex_window_title: "Monitor de uso do Codex",
    antigravity_window_title: "Monitor de uso do Antigravity",
    usage_display_basis: "Base de exibição",
    used_percentage: "% usado",
    remaining_allowance: "Limite restante",
    reset_in: "Reinício em",
    loading: "Carregando",
    fetch_failed: "Falha ao obter",
    retrying: "Tentando novamente",
    not_configured: "Não configurado",
    not_available: "Não disponível",
    display_density: "Densidade de exibição",
    display_density_compact: "Compacto",
    standard_level: "Padrão",
    display_density_detailed: "Detalhado",
    short_window_visibility: "Exibição da janela de 5h",
    short_window_visibility_always: "Sempre exibir",
    short_window_visibility_warning_only: "Somente em uso excessivo",
    short_window_visibility_hidden: "Ocultar",
    short_window_alert_sensitivity: "Sensibilidade de alerta de 5h",
    short_window_alert_sensitivity_sensitive: "Sensível",
    short_window_alert_sensitivity_relaxed: "Relaxada",
};
