use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Atualizar via WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de Uso do Claude Code",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    displayed_ai: "IA a exibir",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Redefinição completa",
    antigravity_model: "Antigravity",
    display_settings: "Configurações de exibição",
    start_with_windows: "Iniciar com o Windows",
    always_on_top: "Sempre no topo",
    reset_position: "Redefinir Posição",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Desconhecido (somente uso)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Ajuda",
    help_display_guide: "Como ler a exibição",
    help_ai_quotas: "Cotas de IA",
    help_readme: "README",
    help_version_information: "Informações da versão",
    help_display_guide_body: concat!(
        "Cota restante / Percentual usado\n",
        "A porcentagem segue a base escolhida nas configurações de exibição.\n\n",
        "5h / 7d / Mo\n",
        "São cotas de cinco horas, sete dias e um mês. Linhas sem conteúdo são omitidas.\n\n",
        "Exibição de tempo\n",
        "Relativo mostra o tempo decorrido em Usado ou o tempo até a redefinição em Restante. Data e hora mostra, em vez disso, a redefinição no horário local.\n\n",
        "Orientação de ritmo\n",
        "Ritmo, diferença do esperado e avisos são referências baseadas no seu ritmo de uso.\n\n",
        "Status\n",
        "Uso zero não é falha de coleta. Não aplicável significa que a cota não existe para o provedor; é diferente de ocultá-la nas configurações."
    ),
    help_ai_quotas_intro: "Cada provedor tem seu próprio sistema de cotas. Nomes parecidos não significam cotas compartilhadas.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Mostra as cotas compartilhadas de 5h e 7d da conta Claude / Claude Code." },
        ProviderHelp { name: "Codex", description: "Mostra as cotas de 5h e 7d disponíveis pelo Codex CLI. Elas são distintas das cotas do aplicativo ChatGPT." },
        ProviderHelp { name: "Antigravity", description: "Mostra as cotas do Antigravity. Elas são distintas das cotas autônomas do Gemini." },
        ProviderHelp { name: "GitHub Copilot", description: "Mostra os AI Credits mensais do GitHub Copilot. O plano escolhido determina a cota; Desconhecido mostra apenas o uso bruto. GitHub Copilot é diferente de Microsoft Copilot." },
    ],
    check_for_updates: "Busca atualizações",
    checking_for_updates: "Buscando por atualizações...",
    updates: "Atualizações",
    update_in_progress: "Uma verificação de atualização já está em andamento.",
    up_to_date: "Você já tem a versão mais recente.",
    up_to_date_short: "Atualizado",
    update_failed: "Não foi possível atualizar automaticamente",
    applying_update: "Aplicando atualização...",
    update_to: "Atualizar para",
    update_available: "Atualização disponível",
    update_prompt_now: "Versão {version} está disponível. Deseja atualizar agora?",
    exit: "Sair",
    show_widget: "Exibir Widget",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "M",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    token_expired_title: "Erro de Autenticação do Claude Code",
    token_expired_body: "Execute 'claude' em um terminal, use '/login' e siga as instruções. Depois disso, atualize ou reinicie este aplicativo.",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    antigravity_token_expired_title: "Erro de Autenticação do Antigravity",
    antigravity_token_expired_body: "Abra o Antigravity e entre novamente. Depois disso, atualize ou reinicie este aplicativo.",
    codex_window_title: "Monitor de uso do Codex",
    antigravity_window_title: "Monitor de uso do Antigravity",
    usage_display_basis: "Base de exibição",
    used_percentage: "% usado",
    remaining_allowance: "Limite restante",
    reset_in: "Reinício em",
    reset_in_separator: " ",
    reset_display: "Exibição de tempo",
    reset_display_relative: "Relativo",
    reset_display_datetime: "Data e hora",
    reset_datetime_day: "Reinício em {day} ({weekday}) às {time}",
    reset_datetime_month_day: "Reinício em {day}/{month} ({weekday}) às {time}",
    reset_datetime_year_month_day: "Reinício em {day}/{month}/{year} ({weekday}) às {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"],
    elapsed: "Decorrido",
    loading: "Carregando",
    authentication_expired: "Autenticação expirada",
    authentication_problem: "Verifique a autenticação",
    credentials_unavailable: "Credenciais não verificáveis",
    fetch_failed: "Falha ao obter",
    not_available: "Não disponível",
    display_density: "Densidade de exibição",
    display_density_compact: "Compacto",
    standard_level: "Padrão",
    display_density_detailed: "Detalhado",
    short_window_visibility: "Modo de exibição",
    short_window_visibility_always: "Sempre exibir",
    short_window_visibility_warning_only: "Somente em uso excessivo",
    short_window_visibility_hidden: "Ocultar",
    short_window_alert_sensitivity: "Sensibilidade de alerta",
    short_window_alert_sensitivity_sensitive: "Sensível",
    short_window_alert_sensitivity_relaxed: "Relaxada",
    weekly_pace_judging: "Avaliando",
    weekly_pace_under_pace: "Abaixo do ritmo",
    weekly_pace_on_track: "Dentro do previsto",
    weekly_pace_slightly_overpacing: "Uso levemente acima",
    weekly_pace_overpacing: "Uso excessivo",
    future_pace_label: "Previsão",
    pace_diff_label: "Diferença do plano",
    exhaustion_label: "Esgotamento estimado",
    exhaustion_before_reset: "cerca de {duration} antes da reinicialização",
    session_window_label: "Janela de 5h",
    weekly_window_label: "Janela de 7d",
    per_day_suffix: "dia",
    per_hour_suffix: "h",
    pace_used_prefix: "Usado",
    pace_remaining_prefix: "Restante",
    popup_layout: "Layout do popup",
    popup_layout_compact: "Compacto",
    popup_layout_standard: "Padrão",
    app_theme: "Tema de cor",
    app_theme_recommended_dark: "Escuro",
    app_theme_light: "Claro",
    app_theme_high_visibility: "Alta visibilidade",
};
