use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Монитор использования Claude Code",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    models: "Модели",
    claude_code_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Настройки",
    start_with_windows: "Запускать вместе с Windows",
    always_on_top: "Всегда поверх других окон",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Показать виджет",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
    usage_display_basis: "Способ отображения",
    used_percentage: "Использовано, %",
    remaining_allowance: "Остаток лимита",
    reset_in: "Сброс через",
    loading: "Загрузка",
    fetch_failed: "Ошибка получения",
    retrying: "Повтор попытки",
    not_configured: "Не настроено",
    not_available: "Недоступно",
    display_density: "Плотность отображения",
    display_density_compact: "Компактно",
    standard_level: "Стандартный",
    display_density_detailed: "Подробно",
    short_window_visibility: "Отображение окна 5ч",
    short_window_visibility_always: "Показывать всегда",
    short_window_visibility_warning_only: "Только при перерасходе",
    short_window_visibility_hidden: "Скрыть",
    short_window_alert_sensitivity: "Чувствительность оповещения 5ч",
    short_window_alert_sensitivity_sensitive: "Высокая",
    short_window_alert_sensitivity_relaxed: "Низкая",
    weekly_pace_judging: "Оценка",
    weekly_pace_under_pace: "С запасом",
    weekly_pace_on_track: "По плану",
    weekly_pace_slightly_overpacing: "Небольшой перерасход",
    weekly_pace_overpacing: "Перерасход",
    future_pace_label: "Прогноз",
    pace_diff_label: "Отклонение от плана",
    exhaustion_label: "Ожидаемое исчерпание",
    exhaustion_before_reset: "примерно за {duration} до сброса",
    session_window_label: "Окно 5ч",
    weekly_window_label: "Окно 7д",
    per_day_suffix: "день",
    per_hour_suffix: "ч",
    pace_used_prefix: "Использовано",
    pace_remaining_prefix: "Осталось",
    popup_layout: "Макет всплывающего окна",
    popup_layout_compact: "Компактно",
    popup_layout_standard: "Стандартный",
    app_theme: "Цветовая тема",
    app_theme_recommended_dark: "Рекомендуемая (тёмная)",
    app_theme_light: "Светлая",
    app_theme_high_visibility: "Высокая контрастность",
};
