use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Обновить через WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Монитор использования Claude Code",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    displayed_ai: "Показывать ИИ",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Полный сброс",
    antigravity_model: "Antigravity",
    display_settings: "Настройки отображения",
    start_with_windows: "Запускать вместе с Windows",
    always_on_top: "Всегда поверх других окон",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Неизвестно (только использование)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Справка",
    help_display_guide: "Как читать данные",
    help_ai_quotas: "Квоты ИИ",
    help_readme: "README",
    help_version_information: "Информация о версии",
    help_display_guide_body: concat!(
        "Остаток / Процент использования\n",
        "Процент соответствует выбранной основе отображения.\n\n",
        "5h / 7d / Mo\n",
        "Это квоты на пять часов, семь дней и месяц. Строки без содержимого скрываются.\n\n",
        "Отображение времени\n",
        "Относительно показывает прошедшее время для Использовано или время до сброса для Остатка. Дата и время вместо этого показывает локальное время сброса.\n\n",
        "Темп использования\n",
        "Ориентир, отклонение от плана и предупреждения основаны на вашем темпе использования.\n\n",
        "Состояния\n",
        "Нулевое использование не является ошибкой получения. Неприменимо означает, что у поставщика нет такой квоты; это не то же самое, что скрытие в настройках."
    ),
    help_ai_quotas_intro: "У каждого поставщика своя система квот. Похожие названия не означают общие квоты.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Показывает общие квоты 5h и 7d учётной записи Claude / Claude Code." },
        ProviderHelp { name: "Codex", description: "Показывает квоты 5h и 7d, доступные через Codex CLI. Они отличаются от квот приложения ChatGPT." },
        ProviderHelp { name: "Antigravity", description: "Показывает квоты Antigravity. Они отличаются от самостоятельных квот Gemini." },
        ProviderHelp { name: "GitHub Copilot", description: "Показывает месячные AI Credits GitHub Copilot. Выбранный план определяет квоту; Неизвестно показывает только общий расход. GitHub Copilot отличается от Microsoft Copilot." },
    ],
    check_for_updates: "Проверить обновления",
    checking_for_updates: "Проверка обновлений...",
    updates: "Обновления",
    update_in_progress: "Проверка обновлений уже выполняется.",
    up_to_date: "У вас уже установлена последняя версия.",
    up_to_date_short: "Актуальная версия",
    update_failed: "Не удалось обновить автоматически",
    applying_update: "Применение обновления...",
    update_to: "Обновить до",
    update_available: "Доступно обновление",
    update_prompt_now: "Доступна версия {version}. Обновить сейчас?",
    exit: "Выход",
    show_widget: "Показать виджет",
    session_window: "5ч",
    weekly_window: "7д",
    monthly_window: "М",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    token_expired_title: "Ошибка авторизации Claude Code",
    token_expired_body: "Запустите 'claude' в терминале, затем используйте '/login' и следуйте инструкциям. После этого обновите или перезапустите приложение.",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    antigravity_token_expired_title: "Ошибка авторизации Antigravity",
    antigravity_token_expired_body: "Откройте Antigravity и войдите снова. После этого обновите или перезапустите приложение.",
    codex_window_title: "Монитор использования Codex",
    antigravity_window_title: "Монитор использования Antigravity",
    usage_display_basis: "Способ отображения",
    used_percentage: "Использовано, %",
    remaining_allowance: "Остаток лимита",
    reset_in: "Сброс через",
    reset_in_separator: " ",
    reset_display: "Отображение времени",
    reset_display_relative: "Относительное",
    reset_display_datetime: "Дата и время",
    reset_datetime_day: "Сброс {day} ({weekday}) в {time}",
    reset_datetime_month_day: "Сброс {day}.{month} ({weekday}) в {time}",
    reset_datetime_year_month_day: "Сброс {day}.{month}.{year} ({weekday}) в {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["вс", "пн", "вт", "ср", "чт", "пт", "сб"],
    elapsed: "Прошло",
    loading: "Загрузка",
    authentication_expired: "Срок аутентификации истёк",
    authentication_problem: "Проверьте аутентификацию",
    credentials_unavailable: "Не удалось проверить данные",
    fetch_failed: "Ошибка получения",
    not_available: "Недоступно",
    display_density: "Плотность отображения",
    display_density_compact: "Компактно",
    standard_level: "Стандартный",
    display_density_detailed: "Подробно",
    short_window_visibility: "Способ отображения",
    short_window_visibility_always: "Показывать всегда",
    short_window_visibility_warning_only: "Только при перерасходе",
    short_window_visibility_hidden: "Скрыть",
    short_window_alert_sensitivity: "Чувствительность предупреждений",
    short_window_alert_sensitivity_sensitive: "Высокая",
    short_window_alert_sensitivity_relaxed: "Низкая",
    weekly_pace_judging: "Оценка",
    weekly_pace_under_pace: "С запасом",
    weekly_pace_on_track: "По плану",
    weekly_pace_slightly_overpacing: "Небольшой перерасход",
    weekly_pace_overpacing: "Перерасход",
    future_pace_label: "Прогноз",
    pace_diff_label: "Отклонение от плана",
    exhaustion_label: "Ожидаемое исчерпание",
    exhaustion_before_reset: "примерно за {duration} до сброса",
    session_window_label: "Окно 5ч",
    weekly_window_label: "Окно 7д",
    per_day_suffix: "день",
    per_hour_suffix: "ч",
    pace_used_prefix: "Использовано",
    pace_remaining_prefix: "Осталось",
    popup_layout: "Макет всплывающего окна",
    popup_layout_compact: "Компактно",
    popup_layout_standard: "Стандартный",
    app_theme: "Цветовая тема",
    app_theme_recommended_dark: "Тёмная",
    app_theme_light: "Светлая",
    app_theme_high_visibility: "Высокая контрастность",
};
