use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量监控",
    refresh: "刷新",
    update_frequency: "更新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    models: "模型",
    claude_code_model: "Claude",
    codex_model: "ChatGPT",
    full_reset: "完整重置",
    antigravity_model: "Antigravity",
    settings: "设置",
    start_with_windows: "开机时启动",
    always_on_top: "始终置顶",
    reset_position: "重置位置",
    language: "语言",
    system_default: "系统默认",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "已有更新检查正在进行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "退出",
    show_widget: "显示小组件",
    session_window: "5h",
    weekly_window: "7d",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "时",
    minute_suffix: "分",
    token_expired_title: "验证错误",
    token_expired_body: "请在终端中运行 'claude'，然后使用 '/login' 并按照提示操作。完成后，请刷新或重新启动此应用程序。",
    codex_token_expired_title: "Codex 验证错误",
    codex_token_expired_body: "请在终端中运行 'codex'，并按照登录提示操作。完成后，请刷新或重新启动此应用程序。",
    antigravity_token_expired_title: "Antigravity 验证错误",
    antigravity_token_expired_body: "请打开 Antigravity 并重新登录。完成后，请刷新或重新启动此应用程序。",
    codex_window_title: "Codex 使用量监控",
    antigravity_window_title: "Antigravity 使用量监控",
    second_suffix: "秒",
    usage_display_basis: "显示方式",
    used_percentage: "已用百分比",
    remaining_allowance: "剩余额度",
    reset_in: "距重置",
    loading: "获取中",
    fetch_failed: "获取失败",
    retrying: "重试中",
    not_configured: "未配置",
    not_available: "不适用",
    display_density: "显示密度",
    display_density_compact: "简洁",
    standard_level: "标准",
    display_density_detailed: "详细",
    short_window_visibility: "5小时窗口显示",
    short_window_visibility_always: "始终显示",
    short_window_visibility_warning_only: "仅超支时显示",
    short_window_visibility_hidden: "不显示",
    short_window_alert_sensitivity: "5小时警告灵敏度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "宽松",
    weekly_pace_judging: "判定中",
    weekly_pace_under_pace: "较为宽裕",
    weekly_pace_on_track: "符合预期",
    weekly_pace_slightly_overpacing: "略有超支",
    weekly_pace_overpacing: "超支",
    future_pace_label: "预计速率",
    pace_diff_label: "与预期偏差",
    exhaustion_label: "预计耗尽",
    exhaustion_before_reset: "重置前约{duration}",
    session_window_label: "5小时窗口",
    weekly_window_label: "7天窗口",
    per_day_suffix: "天",
    per_hour_suffix: "时",
    pace_used_prefix: "已用",
    pace_remaining_prefix: "剩余",
    popup_layout: "弹出窗口布局",
    popup_layout_compact: "简洁",
    popup_layout_standard: "标准",
    app_theme: "配色主题",
    app_theme_recommended_dark: "推荐（深色）",
    app_theme_light: "浅色",
    app_theme_high_visibility: "高可视性",
};
