use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量监控",
    refresh: "刷新",
    update_frequency: "更新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    displayed_ai: "要显示的 AI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "完整重置",
    antigravity_model: "Antigravity",
    display_settings: "显示设置",
    start_with_windows: "开机时启动",
    always_on_top: "始终置顶",
    reset_position: "重置位置",
    language: "语言",
    system_default: "系统默认",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "未知（仅使用量）",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "帮助",
    help_display_guide: "如何阅读显示",
    help_ai_quotas: "AI 配额",
    help_readme: "README",
    help_version_information: "版本信息",
    help_display_guide_body: concat!(
        "剩余配额 / 已用百分比\n",
        "百分比遵循显示设置中选择的显示基准。\n\n",
        "5h / 7d / Mo\n",
        "分别是五小时、七天和每月配额。没有可显示内容的行会被省略。\n\n",
        "时间显示\n",
        "相对模式在已用百分比下显示经过时间，在剩余配额下显示距重置时间。日期时间模式改为显示本地重置日期和时间。\n\n",
        "使用节奏提示\n",
        "参考节奏、与计划的差异及使用过快等警告，是基于使用节奏的参考信息。\n\n",
        "状态区别\n",
        "使用量为零并非获取失败。不适用表示该服务没有此配额，与在设置中隐藏不同。"
    ),
    help_ai_quotas_intro: "每项服务都有自己的配额体系。名称相近并不表示配额共享。",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "显示 Claude / Claude Code 账户共享的 5h 和 7d 配额。" },
        ProviderHelp { name: "Codex", description: "显示通过 Codex CLI 可查看的 5h 和 7d 配额。它们与 ChatGPT 应用的配额不同。" },
        ProviderHelp { name: "Antigravity", description: "显示 Antigravity 的配额。它们与独立 Gemini 的配额不同。" },
        ProviderHelp { name: "GitHub Copilot", description: "显示 GitHub Copilot 的每月 AI Credits。配额取决于所选套餐；套餐未知时仅显示总使用量。GitHub Copilot 与 Microsoft Copilot 不同。" },
    ],
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "已有更新检查正在进行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "退出",
    show_widget: "显示小组件",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "月",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "时",
    minute_suffix: "分",
    token_expired_title: "验证错误",
    token_expired_body: "请在终端中运行 'claude'，然后使用 '/login' 并按照提示操作。完成后，请刷新或重新启动此应用程序。",
    codex_token_expired_title: "Codex 验证错误",
    codex_token_expired_body: "请在终端中运行 'codex'，并按照登录提示操作。完成后，请刷新或重新启动此应用程序。",
    antigravity_token_expired_title: "Antigravity 验证错误",
    antigravity_token_expired_body: "请打开 Antigravity 并重新登录。完成后，请刷新或重新启动此应用程序。",
    codex_window_title: "Codex 使用量监控",
    antigravity_window_title: "Antigravity 使用量监控",
    second_suffix: "秒",
    usage_display_basis: "显示方式",
    used_percentage: "已用百分比",
    remaining_allowance: "剩余额度",
    reset_in: "距重置",
    reset_in_separator: "",
    reset_display: "时间显示",
    reset_display_relative: "相对",
    reset_display_datetime: "日期和时间",
    reset_datetime_day: "{day}（{weekday}）{time}重置",
    reset_datetime_month_day: "{month}月{day}日（{weekday}）{time}重置",
    reset_datetime_year_month_day: "{year}年{month}月{day}日（{weekday}）{time}重置",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["日", "一", "二", "三", "四", "五", "六"],
    elapsed: "已过",
    loading: "获取中",
    authentication_expired: "身份验证已过期",
    authentication_problem: "请检查身份验证",
    credentials_unavailable: "无法确认身份验证信息",
    fetch_failed: "获取失败",
    not_available: "不适用",
    display_density: "显示密度",
    display_density_compact: "简洁",
    standard_level: "标准",
    display_density_detailed: "详细",
    short_window_visibility: "显示方式",
    short_window_visibility_always: "始终显示",
    short_window_visibility_warning_only: "仅超支时显示",
    short_window_visibility_hidden: "不显示",
    short_window_alert_sensitivity: "警告灵敏度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "宽松",
    weekly_pace_judging: "判定中",
    weekly_pace_under_pace: "较为宽裕",
    weekly_pace_on_track: "符合预期",
    weekly_pace_slightly_overpacing: "略有超支",
    weekly_pace_overpacing: "超支",
    future_pace_label: "预计速率",
    pace_diff_label: "与预期偏差",
    exhaustion_label: "预计耗尽",
    exhaustion_before_reset: "重置前约{duration}",
    session_window_label: "5小时窗口",
    weekly_window_label: "7天窗口",
    per_day_suffix: "天",
    per_hour_suffix: "时",
    pace_used_prefix: "已用",
    pace_remaining_prefix: "剩余",
    popup_layout: "弹出窗口布局",
    popup_layout_compact: "简洁",
    popup_layout_standard: "标准",
    app_theme: "配色主题",
    app_theme_recommended_dark: "深色",
    app_theme_light: "浅色",
    app_theme_high_visibility: "高可视性",
};
