use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Actualizar con WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso de Claude Code",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    models: "Modelos",
    claude_code_model: "Claude",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "Configuración",
    start_with_windows: "Iniciar con Windows",
    always_on_top: "Siempre en primer plano",
    reset_position: "Restablecer posición",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    check_for_updates: "Buscar actualizaciones",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Mostrar widget",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Error de autenticación",
    token_expired_body: "Ejecuta 'claude' en una terminal, luego usa '/login' y sigue las indicaciones. Después, actualiza o reinicia esta aplicación.",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    antigravity_token_expired_title: "Error de autenticacion de Antigravity",
    antigravity_token_expired_body: "Abre Antigravity e inicia sesion otra vez. Despues, actualiza o reinicia esta aplicacion.",
    codex_window_title: "Monitor de uso de Codex",
    antigravity_window_title: "Monitor de uso de Antigravity",
    second_suffix: "s",
    usage_display_basis: "Base de visualización",
    used_percentage: "% usado",
    remaining_allowance: "Cupo restante",
    reset_in: "Reinicio en",
    loading: "Cargando",
    fetch_failed: "Error al obtener datos",
    retrying: "Reintentando",
    not_configured: "No configurado",
    not_available: "No disponible",
    display_density: "Densidad de visualización",
    display_density_compact: "Compacto",
    standard_level: "Estándar",
    display_density_detailed: "Detallado",
    short_window_visibility: "Visualización de ventana de 5h",
    short_window_visibility_always: "Mostrar siempre",
    short_window_visibility_warning_only: "Solo si hay sobreuso",
    short_window_visibility_hidden: "Ocultar",
    short_window_alert_sensitivity: "Sensibilidad de alerta de 5h",
    short_window_alert_sensitivity_sensitive: "Sensible",
    short_window_alert_sensitivity_relaxed: "Relajada",
    weekly_pace_judging: "Evaluando",
    weekly_pace_under_pace: "Por debajo del ritmo",
    weekly_pace_on_track: "Según lo previsto",
    weekly_pace_slightly_overpacing: "Ligero sobreuso",
    weekly_pace_overpacing: "Sobreuso",
    future_pace_label: "Previsión",
    pace_diff_label: "Diferencia con lo previsto",
    exhaustion_label: "Agotamiento estimado",
    exhaustion_before_reset: "unas {duration} antes del reinicio",
    session_window_label: "Ventana de 5h",
    weekly_window_label: "Ventana de 7d",
    per_day_suffix: "día",
    per_hour_suffix: "h",
    pace_used_prefix: "Usado",
    pace_remaining_prefix: "Restante",
    popup_layout: "Diseño del popup",
    popup_layout_compact: "Compacto",
    popup_layout_standard: "Estándar",
    app_theme: "Tema de color",
    app_theme_recommended_dark: "Recomendado (oscuro)",
    app_theme_light: "Claro",
    app_theme_high_visibility: "Alta visibilidad",
};
