use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "Actualizar con WinGet";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Monitor de uso de Claude Code",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    displayed_ai: "IA para mostrar",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "Reinicio completo",
    antigravity_model: "Antigravity",
    display_settings: "Configuración de visualización",
    start_with_windows: "Iniciar con Windows",
    always_on_top: "Siempre en primer plano",
    reset_position: "Restablecer posición",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "Desconocido (solo uso)",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "Ayuda",
    help_display_guide: "Cómo leer la pantalla",
    help_ai_quotas: "Cuotas de IA",
    help_readme: "README",
    help_version_information: "Información de versión",
    help_display_guide_body: concat!(
        "Cuota restante / Porcentaje usado\n",
        "El porcentaje sigue la base elegida en la configuración de visualización.\n\n",
        "5h / 7d / Mo\n",
        "Son cuotas de cinco horas, siete días y un mes. Se omiten las filas sin contenido.\n\n",
        "Visualización del tiempo\n",
        "Relativo muestra el tiempo transcurrido en Usado o el tiempo hasta el reinicio en Restante. Fecha y hora muestra en su lugar el reinicio en hora local.\n\n",
        "Orientación de ritmo\n",
        "El ritmo, la diferencia respecto al plan y las advertencias son referencias basadas en tu ritmo de uso.\n\n",
        "Estados\n",
        "Un uso de cero no es un fallo de obtención. No aplicable significa que esa cuota no existe para el proveedor; es distinto de ocultarla en la configuración."
    ),
    help_ai_quotas_intro: "Cada proveedor tiene su propio sistema de cuotas. Nombres similares no implican cuotas compartidas.",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "Muestra las cuotas compartidas de 5h y 7d de la cuenta Claude / Claude Code." },
        ProviderHelp { name: "Codex", description: "Muestra las cuotas de 5h y 7d disponibles mediante Codex CLI. Son distintas de las cuotas de la aplicación ChatGPT." },
        ProviderHelp { name: "Antigravity", description: "Muestra las cuotas de Antigravity. Son distintas de las cuotas autónomas de Gemini." },
        ProviderHelp { name: "GitHub Copilot", description: "Muestra los AI Credits mensuales de GitHub Copilot. El plan elegido determina la cuota; Desconocido solo muestra el uso bruto. GitHub Copilot es distinto de Microsoft Copilot." },
    ],
    check_for_updates: "Buscar actualizaciones",
    checking_for_updates: "Buscando actualizaciones...",
    updates: "Actualizaciones",
    update_in_progress: "Ya hay una comprobación de actualización en curso.",
    up_to_date: "Ya tienes la versión más reciente.",
    up_to_date_short: "Actualizado",
    update_failed: "No se pudo actualizar automáticamente",
    applying_update: "Aplicando actualización...",
    update_to: "Actualizar a",
    update_available: "Actualización disponible",
    update_prompt_now: "La versión {version} está disponible. ¿Quieres actualizar ahora?",
    exit: "Salir",
    show_widget: "Mostrar widget",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "M",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    token_expired_title: "Error de autenticación",
    token_expired_body: "Ejecuta 'claude' en una terminal, luego usa '/login' y sigue las indicaciones. Después, actualiza o reinicia esta aplicación.",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    antigravity_token_expired_title: "Error de autenticacion de Antigravity",
    antigravity_token_expired_body: "Abre Antigravity e inicia sesion otra vez. Despues, actualiza o reinicia esta aplicacion.",
    codex_window_title: "Monitor de uso de Codex",
    antigravity_window_title: "Monitor de uso de Antigravity",
    second_suffix: "s",
    usage_display_basis: "Base de visualización",
    used_percentage: "% usado",
    remaining_allowance: "Cupo restante",
    reset_in: "Reinicio en",
    reset_in_separator: " ",
    reset_display: "Visualización de tiempo",
    reset_display_relative: "Relativo",
    reset_display_datetime: "Fecha y hora",
    reset_datetime_day: "Reinicio {day} ({weekday}) a las {time}",
    reset_datetime_month_day: "Reinicio {day}/{month} ({weekday}) a las {time}",
    reset_datetime_year_month_day: "Reinicio {day}/{month}/{year} ({weekday}) a las {time}",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["dom", "lun", "mar", "mié", "jue", "vie", "sáb"],
    elapsed: "Transcurrido",
    loading: "Cargando",
    authentication_expired: "Autenticación caducada",
    authentication_problem: "Comprueba la autenticación",
    credentials_unavailable: "Credenciales no verificables",
    fetch_failed: "Error al obtener datos",
    not_available: "No disponible",
    display_density: "Densidad de visualización",
    display_density_compact: "Compacto",
    standard_level: "Estándar",
    display_density_detailed: "Detallado",
    short_window_visibility: "Método de visualización",
    short_window_visibility_always: "Mostrar siempre",
    short_window_visibility_warning_only: "Solo si hay sobreuso",
    short_window_visibility_hidden: "Ocultar",
    short_window_alert_sensitivity: "Sensibilidad de alerta",
    short_window_alert_sensitivity_sensitive: "Sensible",
    short_window_alert_sensitivity_relaxed: "Relajada",
    weekly_pace_judging: "Evaluando",
    weekly_pace_under_pace: "Por debajo del ritmo",
    weekly_pace_on_track: "Según lo previsto",
    weekly_pace_slightly_overpacing: "Ligero sobreuso",
    weekly_pace_overpacing: "Sobreuso",
    future_pace_label: "Previsión",
    pace_diff_label: "Diferencia con lo previsto",
    exhaustion_label: "Agotamiento estimado",
    exhaustion_before_reset: "unas {duration} antes del reinicio",
    session_window_label: "Ventana de 5h",
    weekly_window_label: "Ventana de 7d",
    per_day_suffix: "día",
    per_hour_suffix: "h",
    pace_used_prefix: "Usado",
    pace_remaining_prefix: "Restante",
    popup_layout: "Diseño del popup",
    popup_layout_compact: "Compacto",
    popup_layout_standard: "Estándar",
    app_theme: "Tema de color",
    app_theme_recommended_dark: "Oscuro",
    app_theme_light: "Claro",
    app_theme_high_visibility: "Alta visibilidad",
};
