use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "透過 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量監控",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    models: "模型",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "設定",
    start_with_windows: "開機時啟動",
    always_on_top: "永遠置頂",
    reset_position: "重置位置",
    language: "語言",
    system_default: "系統預設",
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "顯示小工具",
    session_window: "5h",
    weekly_window: "7d",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    token_expired_title: "驗證錯誤",
    token_expired_body: "請在終端機中執行 'claude'，然後使用 '/login' 並依照提示操作。完成後，請重新整理或重新啟動此應用程式。",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body: "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    antigravity_token_expired_title: "Antigravity 驗證錯誤",
    antigravity_token_expired_body: "請開啟 Antigravity 並重新登入。完成後，請重新整理或重新啟動此應用程式。",
    codex_window_title: "Codex 使用量監控",
    antigravity_window_title: "Antigravity 使用量監控",
    second_suffix: "秒",
    usage_display_basis: "顯示方式",
    used_percentage: "已用百分比",
    remaining_allowance: "剩餘額度",
    reset_in: "距重置",
    loading: "取得中",
    fetch_failed: "取得失敗",
    retrying: "重試中",
    not_configured: "未設定",
    not_available: "不適用",
    display_density: "顯示密度",
    display_density_compact: "簡潔",
    standard_level: "標準",
    display_density_detailed: "詳細",
    short_window_visibility: "5小時視窗顯示",
    short_window_visibility_always: "永遠顯示",
    short_window_visibility_warning_only: "僅超用時顯示",
    short_window_visibility_hidden: "不顯示",
    short_window_alert_sensitivity: "5小時警示敏感度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "寬鬆",
    weekly_pace_judging: "判定中",
    weekly_pace_under_pace: "較為寬裕",
    weekly_pace_on_track: "符合預期",
    weekly_pace_slightly_overpacing: "略有超用",
    weekly_pace_overpacing: "超用",
    future_pace_label: "預計速率",
    pace_diff_label: "與預期差異",
    exhaustion_label: "預計耗盡",
    exhaustion_before_reset: "重置前約{duration}",
    session_window_label: "5小時視窗",
    weekly_window_label: "7天視窗",
    per_day_suffix: "天",
    per_hour_suffix: "時",
    pace_used_prefix: "已用",
    pace_remaining_prefix: "剩餘",
    popup_layout: "彈出視窗版面",
    popup_layout_compact: "簡潔",
    popup_layout_standard: "標準",
};
