use super::{ProviderHelp, Strings};

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "透過 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Claude Code 使用量監控",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    displayed_ai: "要顯示的 AI",
    claude_code_model: "Claude",
    codex_model: "Codex",
    full_reset: "完整重設",
    antigravity_model: "Antigravity",
    display_settings: "顯示設定",
    start_with_windows: "開機時啟動",
    always_on_top: "永遠置頂",
    reset_position: "重置位置",
    language: "語言",
    system_default: "系統預設",
    github_copilot: "GitHub Copilot",
    github_copilot_plan_unknown: "未知（僅使用量）",
    github_copilot_plan_pro: "Copilot Pro",
    github_copilot_plan_pro_plus: "Copilot Pro+",
    github_copilot_plan_max: "Copilot Max",
    help: "說明",
    help_display_guide: "如何閱讀顯示",
    help_ai_quotas: "AI 配額",
    help_readme: "README",
    help_version_information: "版本資訊",
    help_display_guide_body: concat!(
        "剩餘配額 / 已用百分比\n",
        "百分比依照顯示設定中選擇的基準。\n\n",
        "5h / 7d / Mo\n",
        "分別是五小時、七天和每月配額。沒有可顯示內容的列會省略。\n\n",
        "時間顯示\n",
        "相對模式在已用百分比下顯示經過時間，在剩餘配額下顯示距重設時間。日期時間模式改為顯示本地重設日期和時間。\n\n",
        "使用節奏提示\n",
        "參考節奏、與預定的差異及使用過快等警告，是依使用節奏提供的參考資訊。\n\n",
        "狀態區別\n",
        "使用量為零並非取得失敗。不適用表示該服務沒有此配額，與在設定中隱藏不同。"
    ),
    help_ai_quotas_intro: "每項服務都有自己的配額機制。名稱相近不表示配額共用。",
    help_provider_notes: &[
        ProviderHelp { name: "Claude", description: "顯示 Claude / Claude Code 帳戶共用的 5h 和 7d 配額。" },
        ProviderHelp { name: "Codex", description: "顯示透過 Codex CLI 可查看的 5h 和 7d 配額。它們與 ChatGPT 應用程式的配額不同。" },
        ProviderHelp { name: "Antigravity", description: "顯示 Antigravity 的配額。它們與獨立 Gemini 的配額不同。" },
        ProviderHelp { name: "GitHub Copilot", description: "顯示 GitHub Copilot 的每月 AI Credits。配額依所選方案而定；方案未知時僅顯示總使用量。GitHub Copilot 與 Microsoft Copilot 不同。" },
    ],
    check_for_updates: "檢查更新",
    checking_for_updates: "正在檢查更新...",
    updates: "更新",
    update_in_progress: "已有更新檢查正在進行中。",
    up_to_date: "您已使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "無法自動更新",
    applying_update: "正在套用更新...",
    update_to: "更新至",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否立即更新？",
    exit: "結束",
    show_widget: "顯示小工具",
    session_window: "5h",
    weekly_window: "7d",
    monthly_window: "月",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    token_expired_title: "驗證錯誤",
    token_expired_body: "請在終端機中執行 'claude'，然後使用 '/login' 並依照提示操作。完成後，請重新整理或重新啟動此應用程式。",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body: "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    antigravity_token_expired_title: "Antigravity 驗證錯誤",
    antigravity_token_expired_body: "請開啟 Antigravity 並重新登入。完成後，請重新整理或重新啟動此應用程式。",
    codex_window_title: "Codex 使用量監控",
    antigravity_window_title: "Antigravity 使用量監控",
    second_suffix: "秒",
    usage_display_basis: "顯示方式",
    used_percentage: "已用百分比",
    remaining_allowance: "剩餘額度",
    reset_in: "距重置",
    reset_in_separator: "",
    reset_display: "時間顯示",
    reset_display_relative: "相對",
    reset_display_datetime: "日期和時間",
    reset_datetime_day: "{day}（{weekday}）{time}重置",
    reset_datetime_month_day: "{month}月{day}日（{weekday}）{time}重置",
    reset_datetime_year_month_day: "{year}年{month}月{day}日（{weekday}）{time}重置",
    reset_time_hour: "{hour}:00",
    reset_time_hour_minute: "{hour}:{minute}",
    weekday_short: ["日", "一", "二", "三", "四", "五", "六"],
    elapsed: "已過",
    loading: "取得中",
    authentication_expired: "驗證已過期",
    authentication_problem: "請檢查驗證",
    credentials_unavailable: "無法確認驗證資訊",
    fetch_failed: "取得失敗",
    not_available: "不適用",
    display_density: "顯示密度",
    display_density_compact: "簡潔",
    standard_level: "標準",
    display_density_detailed: "詳細",
    short_window_visibility: "顯示方式",
    short_window_visibility_always: "永遠顯示",
    short_window_visibility_warning_only: "僅超用時顯示",
    short_window_visibility_hidden: "不顯示",
    short_window_alert_sensitivity: "警示敏感度",
    short_window_alert_sensitivity_sensitive: "敏感",
    short_window_alert_sensitivity_relaxed: "寬鬆",
    weekly_pace_judging: "判定中",
    weekly_pace_under_pace: "較為寬裕",
    weekly_pace_on_track: "符合預期",
    weekly_pace_slightly_overpacing: "略有超用",
    weekly_pace_overpacing: "超用",
    future_pace_label: "預計速率",
    pace_diff_label: "與預期差異",
    exhaustion_label: "預計耗盡",
    exhaustion_before_reset: "重置前約{duration}",
    session_window_label: "5小時視窗",
    weekly_window_label: "7天視窗",
    per_day_suffix: "天",
    per_hour_suffix: "時",
    pace_used_prefix: "已用",
    pace_remaining_prefix: "剩餘",
    popup_layout: "彈出視窗版面",
    popup_layout_compact: "簡潔",
    popup_layout_standard: "標準",
    app_theme: "配色主題",
    app_theme_recommended_dark: "深色",
    app_theme_light: "淺色",
    app_theme_high_visibility: "高可視性",
};
